Color output of test && commit || revert

diff --git a/bin/test-and-commit-or-revert b/bin/test-and-commit-or-revert
--- a/bin/test-and-commit-or-revert
+++ b/bin/test-and-commit-or-revert
@@ -12,8 +12,21 @@ passing state.
 
     -h, --help      Show this help.
 END
+
 else
-    cmd="${1:-make test}"
-    echo "Test command: $cmd"
-    git ls-files | entr sh -c "$cmd && git commit -am 'passing' || git reset --hard"
+    test_cmd="${1:-make test}"
+
+    tput setaf 3
+    echo "Testing: $test_cmd\n---"
+    tput sgr0
+
+    # Assemble the command string
+    test="$test_cmd"
+    commit="(git commit -am 'passing' || true)"  # ignore exit code when nothing to commit
+    revert="git reset --hard"
+    tell_succes="tput setaf 2; echo Tests passed! Commit!; tput sgr0"
+    tell_failure="tput setaf 1; echo Tests failed! Revert!; tput sgr0"
+    full_cmd="($test && ($tell_succes; $commit)) || ($tell_failure; $revert)"
+
+    git ls-files | entr sh -c "$full_cmd"
 fi
